//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OrderManagement.DAL
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class OrderManagementDBEntities : DbContext
    {
        public OrderManagementDBEntities()
            : base("name=OrderManagementDBEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<OrderLinesTable> OrderLinesTable { get; set; }
        public DbSet<OrdersTable> OrdersTable { get; set; }
        public DbSet<ProductsTable> ProductsTable { get; set; }
    }
}
