//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OrderManagement.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class OrderLinesTable
    {
        public int Id { get; set; }
        public int ProductID { get; set; }
        public int QuantityOrdered { get; set; }
        public double SellingPrice { get; set; }
        public int OrderNumber { get; set; }
        public Nullable<double> TotalForItem { get; set; }
    
        public virtual OrdersTable OrdersTable { get; set; }
        public virtual ProductsTable ProductsTable { get; set; }
    }
}
