//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OrderManagement.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class OrdersTable
    {
        public OrdersTable()
        {
            this.OrderLinesTable = new HashSet<OrderLinesTable>();
        }
    
        public int OrderNumber { get; set; }
        public System.DateTime OrderDate { get; set; }
        public string DeliveryAddress { get; set; }
        public string OrderStatus { get; set; }
        public Nullable<double> Total { get; set; }
    
        public virtual ICollection<OrderLinesTable> OrderLinesTable { get; set; }
    }
}
