//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OrderManagement.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class ProductsTable
    {
        public ProductsTable()
        {
            this.OrderLinesTable = new HashSet<OrderLinesTable>();
        }
    
        public int Id { get; set; }
        public string Name { get; set; }
        public string Category { get; set; }
        public string SubCategory { get; set; }
        public string Brand { get; set; }
        public string Description { get; set; }
        public double Price { get; set; }
    
        public virtual ICollection<OrderLinesTable> OrderLinesTable { get; set; }
    }
}
